#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ];then
	echo "Source me !"
	exit 1
fi

if [ "$#" -ne "1" ];then
    echo "I need the bitcoind conf path for the sync server!"
    return 1
fi

server_url="http://localhost:5000"
cosigner_url="http://localhost:5001"
tests_dir=$(dirname $(realpath $BASH_SOURCE))

# Start the everythin server..
# Python2 is deprecated !
nohup python "$tests_dir/start_sigserver.py" $1 $server_url &> "$tests_dir/sigserver.log" &
echo $! > "$tests_dir/sigserver_pid"

echo "Started the sync server at url $server_url with conf $1, saving the logs to
$tests_dir/sigserver.log"


# .. And the cosigner
nohup python "$tests_dir/start_cosigningserver.py" $cosigner_url &> "$tests_dir/cosigner.log" &
echo $! > "$tests_dir/cosigner_pid"

echo "Started the cosigning server at url $cosigner_url with conf $1, saving the logs to
$tests_dir/cosigner.log"


# For the functional tests
export SIGSERV_URL=$server_url
export COSIGNER_URL=$cosigner_url

echo "The server url and cosigner url environment vars have been set for pytest."

stop_sigserv () {
	kill $(cat "$tests_dir/sigserver_pid")
}

stop_cosigner () {
	kill $(cat "$tests_dir/cosigner_pid")
}

echo "Stop the server with 'stop_sigserv', and the cosigner with 'stop_cosigner'."
