#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ];then
	echo "Source me !"
	exit 1
fi

if [ "$#" -ne "1" ];then
    echo "I need the bitcoind conf path!"
    return 1
fi

# default
server_url="http://localhost:5000"
tests_dir=$(dirname $(realpath $BASH_SOURCE))
# Python2 is deprecated !
nohup python "$tests_dir/start_sigserver.py" $1 &> "$tests_dir/sigserver.log" &
echo $! > "$tests_dir/sigserver_pid"

echo "Started the signature server at url $server_url with conf $1, saving the logs to
$tests_dir/sigserver.log"

# For the functional tests
export SIGSERV_URL=$server_url

echo "The server url environment var has been set for pytest."

stop_sigserv () {
	kill $(cat "$tests_dir/sigserver_pid")
}

echo "Stop the server with 'stop_sigserv'."
